<?php

namespace ContainerXvFWVqi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookieCheckerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ConnectHolland\CookieConsentBundle\Cookie\CookieChecker' shared autowired service.
     *
     * @return \ConnectHolland\CookieConsentBundle\Cookie\CookieChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['ConnectHolland\\CookieConsentBundle\\Cookie\\CookieChecker'] = new \ConnectHolland\CookieConsentBundle\Cookie\CookieChecker(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack())->getCurrentRequest());
    }
}
