<?php

namespace ContainerXvFWVqi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Cart\CartService' shared autowired service.
     *
     * @return \App\Cart\CartService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Cart\\CartService'] = new \App\Cart\CartService(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
