<?php

namespace ContainerXvFWVqi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PublicController' shared autowired service.
     *
     * @return \App\Controller\PublicController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PublicController'] = $instance = new \App\Controller\PublicController();

        $instance->setContainer(($container->privates['.service_locator.CpcYfID'] ?? $container->load('get_ServiceLocator_CpcYfIDService'))->withContext('App\\Controller\\PublicController', $container));

        return $instance;
    }
}
