<?php

namespace ContainerXvFWVqi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ReviewController' shared autowired service.
     *
     * @return \App\Controller\ReviewController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ReviewController'] = $instance = new \App\Controller\ReviewController(($container->privates['App\\Repository\\ReviewRepository'] ?? $container->load('getReviewRepositoryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.CpcYfID'] ?? $container->load('get_ServiceLocator_CpcYfIDService'))->withContext('App\\Controller\\ReviewController', $container));

        return $instance;
    }
}
