<?php

namespace ContainerXvFWVqi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserSecurityControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\UserSecurityController' shared autowired service.
     *
     * @return \App\Controller\UserSecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\UserSecurityController'] = $instance = new \App\Controller\UserSecurityController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.CpcYfID'] ?? $container->load('get_ServiceLocator_CpcYfIDService'))->withContext('App\\Controller\\UserSecurityController', $container));

        return $instance;
    }
}
