<?php

namespace ContainerJ8Qkgo1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MTDCcM1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MTDCcM1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MTDCcM1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['privates', '.errored..service_locator.MTDCcM1.Symfony\\Bridge\\Doctrine\\ManagerRegistry', NULL, 'Cannot autowire service ".service_locator.MTDCcM1": it references class "Symfony\\Bridge\\Doctrine\\ManagerRegistry" but no such service exists. Try changing the type-hint to "Doctrine\\Persistence\\ManagerRegistry" instead.'],
            'stripeSK' => [$container->getEnv('STRIPE_SK')],
        ], [
            'doctrine' => 'Symfony\\Bridge\\Doctrine\\ManagerRegistry',
            'stripeSK' => '?',
        ]);
    }
}
