<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xxvXrk\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xxvXrk/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container4xxvXrk.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container4xxvXrk\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container4xxvXrk\App_KernelProdContainer([
    'container.build_hash' => '4xxvXrk',
    'container.build_id' => 'b592c42b',
    'container.build_time' => 1692690286,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xxvXrk');
