<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvFWVqi\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvFWVqi/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXvFWVqi.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXvFWVqi\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXvFWVqi\App_KernelProdContainer([
    'container.build_hash' => 'XvFWVqi',
    'container.build_id' => '4f2a8bca',
    'container.build_time' => 1692971667,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvFWVqi');
