controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\PublicController::showHome

app_login:
    path: /login
    controller: App\Controller\UserSecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\UserSecurityController::logout

formations:
    path: /formations
    controller: App\Controller\CategoryController::showFormations

stages:
    path: /stages
    controller: App\Controller\CategoryController::showStages

rdv:
    path: /rdv
    controller: App\Controller\CategoryController::showRdv

ebook: 
    path: /ebook
    controller: App\Controller\CategoryController::showEbook

forum:
    path: /forum
    controller: App\Controller\PublicController::showForum

connexion:
    path: /connexion
    controller: App\Controller\PublicController::showConnexion

mapsite:
    path: /mapsite
    controller: App\Controller\PublicController::showMapsite

valonauteinc:
    path: /valonauteinc
    controller: App\Controller\PublicController::showValonauteinc

careers:
    path: /careers
    controller: App\Controller\PublicController::showCareers

cgu:
    path: /cgu
    controller: App\Controller\PublicController::showCgu

rgpd:
    path: /rgpd
    controller: App\Controller\PublicController::showRgpd

user_home:
    path: /user/home
    controller: App\Controller\UserSecurityController::showHome

dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminSecurityController::showDashboard

show_category:
    path: /category/show
    controller: App\Controller\CategoryController::showCategory

create_category:
    path: /admin/category/create
    controller: App\Controller\CategoryController::createCategory

update_category:
    path: /admin/category/update/{id}
    controller: App\Controller\CategoryController::updateCategory

delete_category:
    path: /admin/category/delete/{id}
    controller: App\Controller\CategoryController::deleteCategory

front_category:
    path: /category/{id}
    controller: App\Controller\CategoryController::showCategoryfront
    requirements:
        id: \d+

front_product:
    path: /product/{id}
    controller: App\Controller\ProductController::showOneProductFront
    requirements:
        id: \d+

show_product:
    path: /product/show
    controller: App\Controller\ProductController::showProducts

create_product:
    path: /admin/product/create
    controller: App\Controller\ProductController::createproduct

update_product:
    path: /admin/product/update/{id}
    controller: App\Controller\ProductController::updateProduct

delete_product:
    path: /admin/product/delete/{id}
    controller: App\Controller\ProductController::deleteProduct

create_article:
    path: /admin/article/create
    controller: App\Controller\ArticleController::createArticle

show_article:
    path: /articles/show
    controller: App\Controller\ArticleController::showArticles

update_article:
    path: /admin/article/update/{id}
    controller: App\Controller\ArticleController::updateArticle

delete_article:
    path: /admin/article/delete/{id}
    controller: App\Controller\ArticleController::deleteArticle

front_onearticle:
    path: /article/{id}
    controller: App\Controller\ArticleController::showOneArticleFront
    requirements:
        id: \d+

blog:
    path: /blog
    controller: App\Controller\ArticleController::showArticlesFront

cart_add:
    path: /cart/add/{id}
    controller: App\Controller\CartController::add
    requirements:
        id: '\d+'  

cart_show:
    path: /cart
    controller: App\Controller\CartController::cartshow

cart_validate:
    path: /cart/validate
    controller: App\Controller\CartController::cartValidate  

cart_delete:
    path: /cart/delete/{id} 
    controller: App\Controller\CartController::delete
    requirements:
        id: '\d+'

order_validation:
    path: /order/validation
    controller: App\Controller\Order\OrderConfirmationController::confirm

order_customer:
    path: /order/list
    controller: App\Controller\Order\OrderListController::index  

order_payment_form:
    path: /order/pay/{id}
    controller: App\Controller\Order\OrderPaymentController::showCard

order_terminate:
    path: /order/terminate/{id}
    controller: App\Controller\Order\OrderPaymentSuccessController::success
    requirements:
        id: '\d+'

account:
    path: /user/account
    controller: App\Controller\UserSecurityController::showaccount

confidence:
    path: /blog/confidence
    controller: App\Controller\ArticleController::showconfidence

relations:
    path: /blog/relations
    controller: App\Controller\ArticleController::showrelations

communications:
    path: /blog/communications
    controller: App\Controller\ArticleController::showcommunications

mailer: 
    path: /mailer
    controller: App\Controller\MailerController::sendEmail

contact:
    path: /contact
    controller: App\Controller\ContactController::contactForm
