<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlhRarb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlhRarb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXlhRarb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXlhRarb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXlhRarb\App_KernelDevDebugContainer([
    'container.build_hash' => 'XlhRarb',
    'container.build_id' => '36518807',
    'container.build_time' => 1692892190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlhRarb');
