<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJe1DhLz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJe1DhLz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJe1DhLz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJe1DhLz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJe1DhLz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Je1DhLz',
    'container.build_id' => '0dfc8276',
    'container.build_time' => 1692287965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJe1DhLz');
