<?php

namespace Proxies\__CG__\ConnectHolland\CookieConsentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CookieConsentLog extends \ConnectHolland\CookieConsentBundle\Entity\CookieConsentLog implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'cookieConsentKey' => [parent::class, 'cookieConsentKey', null],
        "\0".'*'."\0".'cookieName' => [parent::class, 'cookieName', null],
        "\0".'*'."\0".'cookieValue' => [parent::class, 'cookieValue', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'ipAddress' => [parent::class, 'ipAddress', null],
        "\0".'*'."\0".'timestamp' => [parent::class, 'timestamp', null],
        'cookieConsentKey' => [parent::class, 'cookieConsentKey', null],
        'cookieName' => [parent::class, 'cookieName', null],
        'cookieValue' => [parent::class, 'cookieValue', null],
        'id' => [parent::class, 'id', null],
        'ipAddress' => [parent::class, 'ipAddress', null],
        'timestamp' => [parent::class, 'timestamp', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".'*'."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
